version: '3.7'

services:
  postgres:
    image: postgres:13.2-alpine
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shelang
    ports:
      - 5432:5432
    volumes:
      - yugabyte-data:/home/yugabyte/var

volumes:
  yugabyte-data: {}
