version: '3.7'

services:
  yugabyte:
    image: yugabytedb/yugabyte:2.5.3.1-b10
    command: [ "bin/yugabyted", "start", "--daemon=false" ]
    ports:
      - 7000:7000
      - 9000:9000
      - 5433:5433
      - 9042:9042
    volumes:
      - yugabyte-data:/home/yugabyte/var

volumes:
  yugabyte-data: {}
