version: '3.7'

services:
  postgres:
    image: postgres:13.2-alpine
    environment: 
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: shelang
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/home/yugabyte/var

  redis:
    image: redis:6-alpine
    ports:
      - "6380:6379/tcp"

volumes:
  postgres-data: {}
